namespace SOD.StockMarket.Implementation.Cruncher.News
{
    internal class NewsElements
    {
        internal string[] VagueHeadlineStarts = new string[]
        {
            "Economic Puzzle",
            "Mysterious Signals",
            "Unpredictable Forces at Play",
            "Navigating Ambiguity",
            "The Puzzle Deepens",
            "Market Enigma",
            "Unveiling Uncertainty",
            "Amidst Contradictions",
            "Investor Bewilderment",
            "The Grey Zone",
            "Decoding [Product]",
            "Economic Mystery",
            "Uncertainty Unleashed",
            "Ambiguous Outlook",
            "Market Riddles",
            "The Puzzle Unfolds",
            "Intriguing Signals",
            "Uncharted Path",
            "Navigating the Unknown",
            "Market Turmoil",
            "Economic Paradox",
            "Shifting Sands",
            "The Enigma Continues",
            "Market Secrets",
            "Puzzle Pieces",
            "Unraveling the Mystery",
            "Amidst Uncertainty",
            "Market Whirlwind",
            "Profit Conundrum",
            "Ambiguous Landscape",
            "The Unknown Path",
            "Investor Puzzles",
            "Economic Ambiguity",
            "Cryptic Movements",
            "Market Dilemma",
            "The Grey Area",
            "Ambiguous Signals",
            "Economic Quandary",
            "Market Intrigue",
            "Investor Uncertainty",
            "The Enigma Unfolds",
            "Navigating the Economic Fog",
            "Ambiguous Trajectory",
            "The Puzzle Continues",
            "Uncertain Horizons",
        };

        internal string[] VagueHeadlineEnds = new string[]
        {
            "[Company] Maneuvers Through Uncharted Waters",
            "[Stock] Trends Raise Questions Among Investors",
            "[Product] Leaves Market in Speculation",
            "[Industry] Responds to Unseen Challenges",
            "[Company] Grapples With Unresolved Issues",
            "[Stock] Behavior Defies Traditional Analysis",
            "[Product] Launch Sparks Divergent Reactions",
            "[Industry] Adapts to Unforeseen Trends",
            "[Company] Faces Unexpected Market Shifts",
            "[Stock] Fluctuates Amid Ambiguous Economic Climate",
            "[Product] Creates Waves in [Company] Dynamics",
            "[Industry] Charts Unknown Trajectories",
            "[Stock] Movements Raise Eyebrows",
            "[Product] Impact Sparks Debate Among Investors",
            "[Company] Maneuvers Through Unseen Challenges",
            "[Industry] Responds to Cryptic Market Indicators",
            "[Stock] Performance Raises Unanswered Questions",
            "[Product] Launch Leaves Analysts in Speculation",
            "[Company] Adapts to Ambiguous Market Forces",
            "[Industry] Faces Unpredicted Economic Waves",
            "[Stock] Charts a Perplexing Financial Course",
            "[Product] Impact Sparks Debate Among Investors",
            "[Company] Grapples With Unresolved Challenges",
            "[Industry] Responds to Unseen Economic Influences",
            "[Stock] Movements Puzzle Financial Analysts",
            "[Product] Launch Sparks Market Speculation",
            "[Company] Adapts to Ambiguous Market Trends",
            "[Industry] Navigates Unpredictable Economic Forces",
            "[Stock] Swings Defy Conventional Predictions",
            "[Product] Shifts [Company] Financial Dynamics",
            "[Industry] Reacts to Unseen Economic Shifts",
            "[Company] Grapples With Mysterious Market Trends",
            "[Stock] Fluctuations Raise Investor Concerns",
            "[Product] Launch Leaves [Company] in Speculation",
            "[Industry] Navigates Through Ambiguous Economic Climate",
            "[Stock] Trends Spark Debate Among Financial Experts",
            "[Company] Adapts to Unforeseen Market Challenges",
            "[Product] Launch Sparks Debate Among Investors",
            "[Industry] Reacts to Unseen Economic Developments",
            "[Stock] Movements Puzzle Financial Analysts",
            "[Product] Impact Sparks Debate Among Market Experts",
            "[Company] Responds to Unseen Challenges",
            "[Industry] Grapples With Unpredictable Market Forces",
            "[Stock] Behavior Raises Questions Among Investors",
            "[Product] Launch Sparks Market Speculation",
        };
    }
}
