namespace SOD.StockMarket.Implementation.Cruncher.News
{
    internal static class NewsElements
    {
        internal static string[] VagueHeadlineStarts = new string[]
        {
            "Economic Puzzle",
            "Mysterious Signals",
            "Unpredictable Forces at Play",
            "Navigating Ambiguity",
            "The Puzzle Deepens",
            "Market Enigma",
            "Unveiling Uncertainty",
            "Amidst Contradictions",
            "Investor Bewilderment",
            "The Grey Zone",
            "Decoding [Product]",
            "Economic Mystery",
            "Uncertainty Unleashed",
            "Ambiguous Outlook",
            "Market Riddles",
            "The Puzzle Unfolds",
            "Intriguing Signals",
            "Uncharted Path",
            "Navigating the Unknown",
            "Market Turmoil",
            "Economic Paradox",
            "Shifting Sands",
            "The Enigma Continues",
            "Market Secrets",
            "Puzzle Pieces",
            "Unraveling the Mystery",
            "Amidst Uncertainty",
            "Market Whirlwind",
            "Profit Conundrum",
            "Ambiguous Landscape",
            "The Unknown Path",
            "Investor Puzzles",
            "Economic Ambiguity",
            "Cryptic Movements",
            "Market Dilemma",
            "The Grey Area",
            "Ambiguous Signals",
            "Economic Quandary",
            "Market Intrigue",
            "Investor Uncertainty",
            "The Enigma Unfolds",
            "Navigating the Economic Fog",
            "Ambiguous Trajectory",
            "The Puzzle Continues",
            "Uncertain Horizons",
        };

        internal static string[] Headlines = new string[]
        {
            "Patterns Baffle Industry Observers",
            "Indicators Spark Intriguing Speculations",
            "Performance Sparks Enigmatic Debates",
            "Fluctuations Prompt Curious Industry Buzz",
            "Trends Perplex Observers, Ignite Debates",
            "Patterns Puzzle Financial Pundits",
            "Resilience Puzzles Financial Analysts",
            "Indicators Trigger Thoughtful Industry Reflection",
            "Trends Perplex Observers, Ignite Debates",
            "Patterns Puzzle Financial Pundits",
            "Hovers in Mysterious Market Territory",
            "Stirring Speculation in the Investment Realm",
            "Trends Perplex Observers, Ignite Debates",
            "Patterns Puzzle Financial Pundits",
            "Resilience Puzzles Financial Analysts",
            "Indicators Trigger Thoughtful Industry Reflection",
            "Fluctuations Prompt Curious Industry Buzz",
            "Hovers in Mysterious Market Territory",
            "Stirring Speculation in the Investment Realm",
            "Performance Sparks Enigmatic Debates",
            "Fluctuations Prompt Curious Industry Buzz",
            "Trends Perplex Observers, Ignite Debates",
            "Patterns Puzzle Financial Pundits",
            "Resilience Puzzles Financial Analysts",
            "Indicators Trigger Thoughtful Industry Reflection",
            "Market Sentiments Puzzle Financial Experts",
            "Unexpected Trends Raise Questions Among Traders",
            "Investors Analyze Cryptic Stock Movements",
            "Profit Signals Elicit Speculation in Financial Circles",
            "Economic Signals Trigger Thoughtful Reflection",
            "Market Volatility Sparks Unusual Industry Discussions",
            "Investment Realm Reacts to Unseen Market Forces",
            "Stock Patterns Spark Curiosity Among Observers",
            "Financial Analysts Ponder Over Unpredictable Trends",
            "Market Dynamics Raise Industry Speculation",
            "Investors Navigate Through Ambiguous Market Realities",
            "Economic Puzzles Leave Experts in Contemplation",
            "Cryptic Signals Ignite Industry Debates",
            "Unseen Market Influences Prompt Investor Caution",
            "Financial Landscape Shrouded in Uncertainty",
            "Investment Sentiments Perplex Financial Observers",
            "Industry Adapts to Ambiguous Economic Signals",
            "Market Resilience Sparks Thoughtful Analysis",
            "Uncharted Economic Territories Baffle Investors",
            "Profit and Loss Crossroads in Financial Landscape",
            "Investors Grapple with Unseen Fiscal Realities",
            "Cryptic Market Trends Raise Industry Questions",
            "Financial Analysts Probe into Mysterious Profit Trajectories",
            "Market Uncertainties Prompt Unusual Investor Strategies",
            "Investors Navigate through Enigmatic Economic Swirls"
        };
    }
}
